name: Publish

on:
    release:
        types: [created]
jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '16.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: yarn
            - run: yarn buildall
            - run: npm publish
              working-directory: package
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
